# where bowtie2 lives (adjust path if needed)
BOWTIE2        /home/amohs002/miniconda3/envs/ngs/bin/bowtie2
# add a touch more sensitivity + unique hits
BOWTIE2_OPTIONS --very-sensitive

# Databases (name then index prefix)
DATABASE       pberghei     /home/amohs002/projects/research/NGS/pberg/CRK6/data/genomic/bowtie2_index/pberghei/pberghei
DATABASE       hst2t     /home/amohs002/projects/research/NGS/pberg/CRK6/data/genomic/bowtie2_index/hst2t/hst2t
DATABASE       phix      /home/amohs002/projects/research/NGS/pberg/CRK6/data/genomic/bowtie2_index/phix/phix
DATABASE       mmusculus      /home/amohs002/projects/research/NGS/pberg/CRK6/data/genomic/bowtie2_index/mmusculus/mmusculus